version: "3.2"
services:
  centos:
    build: ./
    ports:
      - "22:22"
      - "443:443"
      - "80:80"
      - "3306:3306"
    volumes:
    - ../homework/:/mnt/homework/
    - ./sudoers:/etc/sudoers
    - ../project/:/project/
    command:
      bash -c "/etc/init.d/sshd start && tail -f /dev/null"
    container_name: centos-odp



